#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
filter="$1"

cd $script_dir
scripts=$(find runs -maxdepth 2 -mindepth 1 -executable -type f)
echo $script_dir
for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        echo "filtered: $filter -- $script"
        continue
    else
	./$script
    fi
done

